/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import Gzip from 'react-native-gzip';
import { DocumentDirectoryPath } from 'react-native-fs';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    const targetPath = `${DocumentDirectoryPath}/2f7a8de0befd403b8eff2bf9939fb8a9.tar.gz`
    const sourcePath = `${DocumentDirectoryPath}/2f7a8de0befd403b8eff2bf9939fb8a9`
    console.log(targetPath)
    Gzip.gunzip(targetPath, sourcePath, true).then((res)=>{
      console.log(res)
    })
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Gzip example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
