/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { useEffect } from 'react';
import { StyleSheet, View, Text } from 'react-native';
import Gzip from '@fengweichong/react-native-gzip';
import { DocumentDirectoryPath } from 'react-native-fs';
console.log(Gzip)
export default function App() {
  useEffect(() => {
    console.log(DocumentDirectoryPath)

    const tarSource = `${DocumentDirectoryPath}/test.tar`;
    const tarTarget = `${DocumentDirectoryPath}/tar`;

    Gzip.unTar(tarSource, tarTarget, true).then((result) => {
      console.log(result)
    }).catch((err) => {
      console.error(err)
    })

    const gzipTarSource = `${DocumentDirectoryPath}/test.tar.gz`;
    const gzipTarTarget = `${DocumentDirectoryPath}/gzipTar`;

    Gzip.unGzipTar(gzipTarSource, gzipTarTarget, true).then((result) => {
      console.log(result)
    }).catch((err) => {
      console.error(err)
    })
  }, [])
  return (
    <View style={styles.container}>
      <Text>请将文件拷贝至指定目录测试</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
